; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -backprop -S %s | FileCheck %s

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define double @tinkywinky(double %x) {
; CHECK-LABEL: @tinkywinky(
; CHECK-NEXT:    [[CALL:%.*]] = tail call double @llvm.cos.f64(double [[X:%.*]])
; CHECK-NEXT:    ret double [[CALL]]
;
  %patatino = tail call double @llvm.fabs.f64(double %x)
  %call = tail call double @llvm.cos.f64(double %patatino)
  ret double %call
}

declare double @llvm.fabs.f64(double)
declare double @llvm.cos.f64(double)
